### PR TITLE
Fix Target for Deref of stdsync::TracingMutexGuard

### PR DESCRIPTION
**Pull request by quisar**
This fixes https://github.com/bertptrs/tracing-mutex/issues/6

### CODE REVIEW

**Comment by bertptrs** [comment]
Thank you for your contribution! (and the others you made) The choice was intentionally made to deref to the `MutexGuard`, counting on deref coercion to make up the difference. The rationale was that some APIs might actually need a reference to the internal MutexGuard.

I think this assumption was incorrect, and for the cases that it might be necessary we can add some functions to expose it, so I agree with your changes.

Unfortunately, over the past year the code has rotted a bit and no longer passes CI. I'll first try to fix that, and then get back to yours.

**Comment by bertptrs** [comment]
@quisar Could you rebase your PRs on the current master? Then the CI should pass once more.

**Comment by quisar** [comment]
Done.

**Comment by bertptrs** [comment]
Thank you!

**Pull request merged**
